### ISSUE TITLE
LF function crashes when data is not correctly read

### ISSUE THREAD

**Issue by Gabriel-p** [asteca/asteca#143]
Fix the following (probably related to the data file having 12 columns and being read as having 7):

````
Analizing cluster L109 (auto).
Data obtained from input file (N_stars: 3192).
 Entries rejected: 6463.
  WARNING: 67% of stars rejected.
Frame's 2D histogram obtained
Auto center found: (950.753, 1152.87) px.
Radial density profile (RDP) calculated.
Field density calculated (7.7E-04 stars/px^2).
Auto radius found: 355.75 px.
  WARNING: tidal radius could not be obtained.
  WARNING: core radius could not be obtained.
Approximate number of members in cluster obtained (75).
Contamination index obtained (0.84).
Stars accepted/rejected based on their errors.
Stars separated in/out of cluster's boundaries.
  WARNING: Number of FR defined (10) larger than
  the maximum allowed (8). Using max number.
  WARNING: no field regions left after removal of those
  with less than 4 stars.

!!! --> /L109.MAG could not be processed <-- !!!

Traceback (most recent call last):
  File "asteca.py", line 41, in main
    af(mypath, cl_file, ip_list, R_in_place)
  File "/path/asteca-master/functions/func_caller.py", line 126, in asteca_funcs
    field_region)
  File "/path/asteca-master/functions/phot_analysis/get_lf.py", line 50, in lf
    mag_cl = zip(*cl_region)[3]
IndexError: list index out of range

````

**Comment by Gabriel-p** [comment]
This is inevitable but should the code push forward? Not being able to obtain a LF is a big  issue and perhaps it is good that the code halts, alerting the user that there's something wrong with the photometric data input (or the params_input file).

**Comment by Gabriel-p** [comment]
This issues was addressed with this commit: https://github.com/asteca/asteca/commit/c55f036df581989f48c72c23d2fa64238ba5a6cb
