### ISSUE TITLE
top_tiers fails and prevents final image from being generated

### ISSUE THREAD

**Issue by Gabriel-p** [asteca/asteca#147]
The plotting of the top tiers should be placed inside try statements to prevent this. Also, see what went wrong here:

````
!!! --> /NGC1852.OUT could not be processed <-- !!!

Traceback (most recent call last):
  File "asteca_01.py", line 48, in main
    af(mypath, cl_file, ip_list, R_in_place, file_end)
  File "/home/gperren/asteca/functions/func_caller.py", line 172, in asteca_funcs
    completeness, bf_return)
  File "/home/gperren/asteca/functions/out/top_tiers.py", line 138, in get_top_tiers
    col_data, ip_list, err_lst, completeness)
  File "/home/gperren/asteca/functions/out/top_tiers.py", line 81, in plot_top_tiers
    top_tiers_plot.pl_bf_synth_cl(n, *args)
  File "/home/gperren/asteca/functions/out/top_tiers_plot.py", line 75, in pl_bf_synth_cl
    text1 = '$N = {}$\n'.format(len(synth_clst[0]))
IndexError: index out of bounds
````

Probably related to the best params assignment failing miserably:

````
Using Genetic Algorithm (dolphin/knuth).
  10% done 	 (0.0001, 6, 0, 18, 0, 0)
  20% done 	 (0.0001, 6, 0, 18, 0, 0)
  30% done 	 (0.0001, 6, 0, 18, 0, 0)
  40% done 	 (0.0001, 6, 0, 18, 0, 0)
  50% done 	 (0.0001, 6, 0, 18, 0, 0)
  60% done 	 (0.0001, 6, 0, 18, 0, 0)
Best fit params obtained.
````

Rest of the data just in case:

````
Analizing cluster NGC1852 (semi).
Data obtained from input file (N_stars: 62525).
Frame's 2D histogram obtained
Semi center found: (3709.49, 4653.33) px.
Radial density profile (RDP) calculated.
Field density calculated (5.0E-03 stars/px^2).
Auto radius found: 619.621 px.
Tidal radius obtained: 693.823 px.
Approximate number of members in cluster obtained (180).
Contamination index obtained (0.98).
Stars accepted/rejected based on their errors.
Stars separated in/out of cluster's boundaries.
Using defined number of field regions (10).
LF and Completeness magnitude levels obtained.
Integrated color magnitude distribution obtained (0.97).
Obtaining p_value for cluster region vs field regions.
````

**Comment by Gabriel-p** [comment]
What went wrong is that the lower mass is so small (0) that the synthetic clusters could not be generated since they lacked even a single star.
