### ISSUE TITLE
IndexError: index out of bounds (astroML related)

### ISSUE THREAD

**Issue by Gabriel-p** [asteca/ASteCA#251]
Found when processing L39, happened when the bootstrap was close to finishing. Seems to be related to the `astroML` package.

```

Traceback (most recent call last):
  File "asteca_05.py", line 58, in main
    af(cl_file, ip_list, R_in_place)
  File "/home/gperren/asteca/functions/func_caller.py", line 163, in asteca_funcs
    bf_return = bfsc(err_lst, red_return[0], completeness, ip_list)
  File "/home/gperren/asteca/functions/best_fit/best_fit_synth_cl.py", line 131, in best_fit
    isoch_fit_params)
  File "/home/gperren/asteca/functions/best_fit/best_fit_synth_cl.py", line 73, in params_errors
    completeness, ip_list, st_dist_mass)
  File "/home/gperren/asteca/functions/best_fit/bootstrap_func.py", line 50, in bootstrap
    obs_cl = prep(obs_cl_r)
  File "/home/gperren/asteca/functions/best_fit/obs_clust_prepare.py", line 45, in prepare
    bin_edges = bin_edges_f(bin_method, mag_col_cl)
  File "/home/gperren/asteca/functions/phot_analysis/local_diag_clean.py", line 42, in bin_edges_f
    bin_edges.append(hist(mag_col, bins=bin_method)[1])
  File "/usr/local/lib/python2.7/dist-packages/astroML/plotting/hist_tools.py", line 65, in hist
    dx, bins = knuth_bin_width(x, True)
  File "/usr/local/lib/python2.7/dist-packages/astroML/density_estimation/histtools.py", line 226, in knuth_bin_width
    M = optimize.fmin(knuthF, len(bins0))[0]
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 351, in fmin
    res = _minimize_neldermead(func, x0, args, callback=callback, **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 443, in _minimize_neldermead
    fxr = func(xr)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 261, in function_wrapper
    return function(x, *args)
  File "/usr/local/lib/python2.7/dist-packages/astroML/density_estimation/histtools.py", line 155, in __call__
    return self.eval(M)
  File "/usr/local/lib/python2.7/dist-packages/astroML/density_estimation/histtools.py", line 173, in eval
    nk, bins = np.histogram(self.data, bins)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 199, in histogram
    sa.searchsorted(bins[-1], 'right')]
IndexError: index out of bounds
```

Saw it again with a synthetic MASSCLEAN cluster, Could not reproduce:

```
Traceback (most recent call last):
  File "asteca_01.py", line 58, in main
    af(cl_file, ip_list, R_in_place)
  File "/home/gperren/asteca/functions/func_caller.py", line 165, in asteca_funcs
    bf_return = bfsc(err_lst, red_return[0], completeness, ip_list)
  File "/home/gperren/asteca/functions/best_fit/best_fit_synth_cl.py", line 95, in best_fit
    obs_clust = prep(memb_prob_avrg_sort)
  File "/home/gperren/asteca/functions/best_fit/obs_clust_prepare.py", line 45, in prepare
    bin_edges = bin_edges_f(bin_method, mag_col_cl)
  File "/home/gperren/asteca/functions/phot_analysis/local_diag_clean.py", line 42, in bin_edges_f
    bin_edges.append(hist(mag_col, bins=bin_method)[1])
  File "/usr/local/lib/python2.7/dist-packages/astroML/plotting/hist_tools.py", line 65, in hist
    dx, bins = knuth_bin_width(x, True)
  File "/usr/local/lib/python2.7/dist-packages/astroML/density_estimation/histtools.py", line 226, in knuth_bin_width
    M = optimize.fmin(knuthF, len(bins0))[0]
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 351, in fmin
    res = _minimize_neldermead(func, x0, args, callback=callback, **opts)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 443, in _minimize_neldermead
    fxr = func(xr)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 261, in function_wrapper
    return function(x, *args)
  File "/usr/local/lib/python2.7/dist-packages/astroML/density_estimation/histtools.py", line 155, in __call__
    return self.eval(M)
  File "/usr/local/lib/python2.7/dist-packages/astroML/density_estimation/histtools.py", line 173, in eval
    nk, bins = np.histogram(self.data, bins)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 199, in histogram
    sa.searchsorted(bins[-1], 'right')]
IndexError: index out of bounds
```

**Comment by Gabriel-p** [comment]
Haven't seen this issue again, can't reproduce, and astroML is no longer used.
