### ISSUE TITLE
Crash when obtaining error curve

### ISSUE THREAD

**Issue by Gabriel-p** [asteca/ASteCA#256]
There is a bug in `best_fit/synth_cl_err.py`. For some photometric data ([example](https://github.com/asteca/ASteCA/files/192429/B48.OUT.tar.gz)) the `scipy.optimize.curve_fit` function fails with a `TypeError` (see below) rather than a `RuntimeError`.

Since the code only catches the latter, it crashes. Using simply `except` fixes this.

```

Traceback (most recent call last):
  File "asteca.py", line 58, in main
    af(cl_file, ip_list, R_in_place)
  File "/media/rest/github/asteca-project/asteca/functions/func_caller.py", line 154, in asteca_funcs
    err_lst = sce(phot_data, err_pck)
  File "/media/rest/github/asteca-project/asteca/functions/best_fit/synth_cl_err.py", line 66, in synth_clust_err
    popt_mc = get_m_c_errors(mag, mag_value, e_mag_v)
  File "/media/rest/github/asteca-project/asteca/functions/best_fit/synth_cl_err.py", line 21, in get_m_c_errors
    popt_mc, dummy = curve_fit(ef.exp_3p, mag_value, e_mc_v)
  File "/home/gabriel/.local/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 578, in curve_fit
    res = leastsq(func, p0, args=args, full_output=1, **kw)
  File "/home/gabriel/.local/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 374, in leastsq
    raise TypeError('Improper input: N=%s must not exceed M=%s' % (n, m))
TypeError: Improper input: N=3 must not exceed M=2
```

**Comment by Gabriel-p** [comment]
Realized that the code was trying to fit a 3 parameter exponential with only two points, and this is why it failed.
